services:
  - type: web
    name: lyro-react
    runtime: node
    plan: free
    buildCommand: npm install && cd vite && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /healthz
